### ISSUE TITLE
Where can I find some info on the cap sensors

### ISSUE THREAD

**Issue by magnum95** [LELO-Devs/F1S-SDK#7]
Hi there,
first of all, great toy to play around! I started writing some Code for it and I  have a question: in which Depth are the sensors located? I mean which Depth will trigger each sensor?
thanks.

**Comment by goranche** [comment]
huh... 🤔 excellent question 😅 I have no idea, to be honest 🙈
but will try to find out and get back to you 👍

**Comment by goranche** [comment]
@magnum95 the sensors are located at approximately 25, 36, 46, 57, 67, 78, 88 and the final one at 103mm of depth. I say approximately because I rounded the numbers to the nearest mm 😉

given the nature of the sensors and the chamber being stretchy (with the walls being silicone) do note that the sensors might trigger at differing depths, depending on many factors, including, but not limited to:

- depth of thrust (captain obvious made me write this 🙈)
- angle of entry
- angle of device rotation
- physical characteristics of user
- ...

Hope this answers your question 😉 

feel free to close the issue if it does 👍

**Comment by magnum95** [comment]
wow, that was quick. Thanks a lot!

**Comment by goranche** [comment]
@magnum95 we aim to please 🙈
(pun intended 😅)
